### ISSUE TITLE
Logging all incoming requests

### ISSUE THREAD

**Issue by kgish** [seancribbs/webmachine-ruby#211] opened 2015-01-02 13:15 UTC
Where's the best place to log the complete request when it first arrives?

I tried following the example for in `examples/logging.rb` using `LogListener` but get the following error message:
```
uninitialized constant Webmachine::Events
```
Any other example?

**Comment by bethesque** [comment] 2015-01-02 21:18
I made a Gemfile with `gem "webmachine"`, copied the logging example file exactly to a file called bethtest.rb (actually, I set `config.port = 8888` because I couldn't remember what port it started on by default!), ran `bundle` and `bundle exec ruby bethtest.rb` - and it worked for me.

```
[2015-01-03T08:10:45+11:00] method=GET uri=http://localhost:8888/ code=200 resource=HelloResource time=1.4100
```

**Comment by kgish** [comment] 2015-01-02 21:48
Oops. I've been running `ruby server.rb` and now realize that I should probably be running `bundle exec ruby server.rb` instead.

Frustrations galore for a struggling newbie I'm afraid.

**Comment by bethesque** [comment] 2015-01-02 21:56
We've all done that! A lot of people make aliases like `beru` for `bundle exec ruby` and `ber` for `bundle exec rake` because it's easy to forget, and annoying to type the full command all the time.

**Comment by bethesque** [comment] 2015-01-03 09:56
Closeable?

**Comment by kgish** [comment] 2015-01-03 10:07
Like my other issue [#205](https://github.com/seancribbs/webmachine-ruby/issues/205), still same problem :(

**Comment by bethesque** [comment] 2015-01-03 10:11
Without being able to pair with you, it's very hard to see what's going wrong! Are you using rbenv or chruby or rvm? Given none of us can reproduce the issues, I'd suspect it's something to do with your setup, rather than the Webmachine code itself. Can you post the exact commands to replicate, starting with the clone, and include the stack trace?

**Comment by kgish** [comment] 2015-01-03 10:51
I'm using `rvm` and you can can reproduce it by cloning my github project [webmachine-roar-template](https://github.com/kgish/ruby-webmachine-roar-template) and trying it out yourself.

**Comment by bethesque** [comment] 2015-01-03 10:57
```
bethtemp $ git clone git@github.com:kgish/ruby-webmachine-roar-template.git
Cloning into 'ruby-webmachine-roar-template'...
remote: Counting objects: 256, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 256 (delta 6), reused 0 (delta 0)
Receiving objects: 100% (256/256), 73.59 KiB | 93.00 KiB/s, done.
Resolving deltas: 100% (158/158), done.
Checking connectivity... done.
bethtemp $ cd ruby-webmachine-roar-template/
ruby-webmachine-roar-template $ bundle install
warning: ignoring extraneous `ruby-' prefix in version `ruby-2.1.5'
         (set by /Users/Bethany/bethtemp/ruby-webmachine-roar-template/.ruby-version)
Fetching gem metadata from http://rubygems.org/.......
Fetching additional metadata from http://rubygems.org/..
Fetching https://github.com/bernd/webmachine-test.git
Installing rake 10.4.2
Installing multi_json 1.0.3
Installing i18n 0.6.0
Installing builder 3.0.0
Installing hike 1.2.1
Installing erubis 2.7.0
Installing rack 1.3.5
Installing jwt 1.2.0
Using multipart-post 2.0.0
Installing gem_config 0.3.1
Installing tilt 1.3.3
Installing fuzzyurl 0.2.2
Installing uri_template 0.7.0
Installing httpauth 0.2.1
Using coderay 1.1.0
Installing hitimes 1.2.2
Installing crack 0.1.8
Installing json 1.6.1
Installing diff-lcs 1.1.3
Installing http_parser.rb 0.6.0
Installing formatador 0.2.5
Installing rb-fsevent 0.9.4
Installing lumberjack 1.0.9
Installing nenv 0.1.1
Using method_source 0.8.2
Using slop 3.6.0
Using thor 0.19.1
Installing hooks 0.1.4
Installing ffi 1.9.6
Installing json_pure 1.6.1
Installing methodize 0.2.0
Installing eventmachine 1.0.4
Installing respondie 0.9.0
Installing rspec-core 2.7.1
Installing rspec-mocks 2.7.0
Installing sqlite3 1.3.4
Using bundler 1.7.10
Installing nokogiri 1.5.0
Installing activesupport 3.1.3
Installing webmachine 0.3.0
Installing rack-mount 0.8.3
Installing sequel 4.17.0
Installing rack-cache 1.1
Using faraday 0.9.0
Installing rack-conneg 0.1.5
Installing rack-test 0.6.1
Installing timers 4.0.1
Installing fridge 0.2.2
Installing sprockets 2.0.3
Using pry 0.10.1
Installing rb-inotify 0.9.5
Installing httparty 0.7.4
Installing rspec-expectations 2.7.0
Installing em-websocket 0.5.1
Installing sqlite3-ruby 1.3.3
Installing representable 0.9.2
Using webmachine-test 0.0.0 from https://github.com/bernd/webmachine-test.git (at master)
Installing hypertemplate 1.2.1
Installing activemodel 3.1.3
Installing hyperresource 0.9.0
Installing oauth2 0.6.0
Installing celluloid 0.16.0
Installing rspec 2.7.0
Installing aptible-auth 0.2.1
Installing listen 2.8.4
Installing guard 2.10.5
Installing actionpack 3.1.3
Installing medie 1.0.0
Installing guard-livereload 1.3.0
Installing restfulie 1.0.3
Installing roar 0.8.1
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from httparty:
When you HTTParty, you must party hard!
Post-install message from sqlite3-ruby:

#######################################################

Hello! The sqlite3-ruby gem has changed it's name to just sqlite3.  Rather than
installing `sqlite3-ruby`, you should install `sqlite3`.  Please update your
dependencies accordingly.

Thanks from the Ruby sqlite3 team!

<3 <3 <3 <3

#######################################################

ruby-webmachine-roar-template $ bundle exec ruby server.rb
warning: ignoring extraneous `ruby-' prefix in version `ruby-2.1.5'
         (set by /Users/Bethany/bethtemp/ruby-webmachine-roar-template/.ruby-version)

USERS
#    id   name            username   email                     password        admin
---- ---- --------------- ---------- ------------------------  ---------       -----
1    1    Kiffin Gish     kiffin     kiffin.gish@planet.nl     pindakaas       yes
2    2    Henri Bergson   henri      henri.bergson@planet.nl   escargot        no

PRODUCTS
#    id   name            category        price
---- ---- --------------- --------------- -----
1    1    rabbit          unknown         3401
2    2    jupiter         food            9592
3    3    suitcase        clothing        2405
4    4    pizza           person          6474
5    5    beer            car             9490
6    6    dragon          clothing        863
7    7    dime            book            9076
8    8    george          person          9085
9    9    apple           animal          8655

[2015-01-03 21:20:41] INFO  WEBrick 1.3.1
[2015-01-03 21:20:41] INFO  ruby 2.1.5 (2014-11-13) [x86_64-darwin14.0]
[2015-01-03 21:20:41] INFO  Webmachine::Adapters::WEBrick::Server#start: pid=93851 port=8080

```

Is the bug on master? This worked for me.

**Comment by bethesque** [comment] 2015-01-03 11:00
Ah, I've found the commented out LogListener, will investigate.

**Comment by bethesque** [comment] 2015-01-03 11:04
You're using webmachine 0.3.0. Do a `bundle update webmachine` (you'll get 1.2.2) and it will work. This will probably fix the other issue too!

**Comment by kgish** [comment] 2015-01-03 11:21
Yes indeed, ran `bundle update webmachine` and all problems fixed!!!

**Comment by Asmod4n** [comment] 2015-01-03 11:22
@kgish maybe you could also just run ```bundle update``` this will update everything to the latest versions, which might break stuff tho.

**Comment by kgish** [comment] 2015-01-03 11:30
Thanks for the tip, done.

**Comment by bethesque** [comment] 2015-01-03 11:30
Good point. I just ran it and there were quite a few updates, some of them major versions. The server started up afterward though, so you should be right.

**Comment by kgish** [comment] 2015-01-03 11:35
Starts fine now but running `monitor-products` chokes ... will investigate.

**Comment by kgish** [comment] 2015-01-03 12:18
After running `bundle update webmachine` I see that the following (incorrect) JSON is returned:
```
 Webmachine-Ruby/1.2.2 WEBrick/1.3.1
{"products"=>[{"name"=>"pizza", "category"=>"food", "price"=>500, "links"=>[{"rel"=>"self",
"href"=>"/products/1"}]}, {"name"=>"shoes", "category"=>"clothing", "price"=>2000, "links"=>
[{"rel"=>"self", "href"=>"/products/2"}]}, {"name"=>"laptop", "category"=>"computer",
"price"=>500000, "links"=>[{"rel"=>"self", "href"=>"/products/3"}]}]}
```
whereas for the older version it was correct:
```
Webmachine-Ruby/0.3.0 WEBrick/1.3.1
{"products"=>[{"product"=>{"id"=>1, "name"=>"pizza", "category"=>"food", "price"=>500, "links"=>[]}}, {"product"=>{"id"=>2, "name"=>"shoes", "category"=>"clothing", "price"=>2000, "links"=>[]}}, {"product"=>{"id"=>3, "name"=>"laptop", "category"=>"computer", "price"=>500000, "links"=>[]}}]}
```
Could it be that the ROAR gems I'm using break?
```
require 'roar/representer/json'
require 'roar/representer/feature/hypermedia'
```

**Comment by Asmod4n** [comment] 2015-01-03 12:20
The roar version you used was three years old, its to be expected they changed the api since then.
Maybe try relaxing the roar requirement in your Gemfile to something newer and see what they have changed?

**Comment by bethesque** [comment] 2015-01-03 21:25
The newer version is actually what I would expect to see, and is conventional JSON. There's no need to indicate that the hash is a "product", because you've already indicated that this is an array of products in the top node. JSON is much less verbose that way than XML. Given that JSON is an "Object Notation", imagine you were getting the name of the first product - you'd expect to go response.products[0].name, not response.products[0].product.name.

Either way, as @Asmod4n said, that's a Roar thing, not a Webmachine thing.

**Comment by bethesque** [comment] 2015-01-03 21:27
Btw, @apotonick is very helpful with questions about Roar.

**Comment by kgish** [comment] 2015-01-03 21:41
Updated but it broke too much. So will go with the older version for the time being and later can upgrade.

**Comment by apotonick** [comment] 2015-01-03 21:59
@kgish Try to isolate the problem with the incorrect JSON. Do something along this.

```ruby
SongRepresenter.prepare(model).to_json
```
If that is the wrong JSON, your representer has changed. Otherwise, it's a webmachine problem.

**Comment by bethesque** [comment] 2015-01-03 22:17
Webmachine is not Rails! It doesn't mix weird stuff into your models without you knowing! I take it back about you being helpful :P

**Comment by apotonick** [comment] 2015-01-03 23:13
Hahaha I am pretty sure it _is_ a change in Roar given that @kgish's version is years old, that's why I said that! :wink:

**Comment by kgish** [comment] 2015-01-04 18:48
Am now switching over to the newest versions, will provide feedback shortly ...

**Comment by bethesque** [comment] 2015-01-15 06:12
Can we close this issue now?

**Closed** 2015-01-15 18:56 UTC
